pool:
    vmImage: "ubuntu-latest"
jobs:
- job: preview
  steps:
  - task: UseNode@1
    inputs:
      version: '20.x'
  - task: Npm@1
    inputs:
      command: install
  - task: Pulumi@1
    inputs:
      command: 'preview'
      stack: 'pierskarsenbarg/azure-devops-typescript/dev'
      cwd: "/path/to/subfolder"

- job: manualintervention
  dependsOn: preview
  pool: server
  steps:
  - task: ManualValidation@0
    inputs:
      instructions: "If preview looks good then proceed"

- job: update
  dependsOn: manualintervention
  steps:
  - task: UseNode@1
    inputs:
      version: '20.x'
  - task: Npm@1
    inputs:
      command: install
  - task: Pulumi@1
    inputs:
      command: 'up'
      stack: 'pierskarsenbarg/azure-devops-typescript/dev'
      args: '--yes --skip-preview'
  - script: |
      echo "##vso[task.setvariable variable=petName;isOutput=true]$(pulumi stack output petName)"
    displayName: 'Set stack outputs as variables'
    name: 'pulumi'
  - script: echo $(pulumi.petName)
    displayName: 'Run a one-line script' 

- job: destroy
  dependsOn: update
  steps:
  - task: UseNode@1
    inputs:
      version: '20.x'
  - task: Npm@1
    inputs:
      command: install
  - task: Pulumi@1
    inputs:
      command: 'destroy'
      stack: 'pierskarsenbarg/azure-devops-typescript/dev'
      args: '--yes --skip-preview' 
